// src/data/dummyData.ts
export const dummyArray = [
  {
    id: 1,
    name: "Alice",
    age: 25,
    registeredOn: new Date("2023-01-15"),
    score: 89.5,
    isActive: true,
    notes: "First registered user",
  },
  {
    id: 2,
    name: "Bob",
    age: 30,
    registeredOn: new Date("2023-02-20"),
    score: 75.0,
    isActive: false,
    notes: "On leave since June",
  },
  {
    id: 3,
    name: "Charlie",
    age: 35,
    registeredOn: new Date("2023-03-25"),
    score: 92.7,
    isActive: true,
    notes: "Recently promoted",
  },
  {
    id: 4,
    name: "Diana",
    age: 28,
    registeredOn: new Date("2023-04-30"),
    score: 84.2,
    isActive: true,
    notes: "Part-time member",
  },
  {
    id: 5,
    name: "Evan",
    age: 22,
    registeredOn: new Date("2023-05-15"),
    score: 68.4,
    isActive: false,
    notes: "Pending verification",
  },
  {
    id: 6,
    name: "Fiona",
    age: 29,
    registeredOn: new Date("2023-06-10"),
    score: 77.3,
    isActive: true,
    notes: "Recently joined the team",
  },
  {
    id: 7,
    name: "George",
    age: 33,
    registeredOn: new Date("2023-07-05"),
    score: 90.1,
    isActive: true,
    notes: "Key project contributor",
  },
  {
    id: 8,
    name: "Hannah",
    age: 27,
    registeredOn: new Date("2023-08-01"),
    score: 73.8,
    isActive: false,
    notes: "Currently on sabbatical",
  },
  {
    id: 9,
    name: "Ian",
    age: 31,
    registeredOn: new Date("2023-09-12"),
    score: 85.6,
    isActive: true,
    notes: "Experienced mentor",
  },
  {
    id: 10,
    name: "Julia",
    age: 26,
    registeredOn: new Date("2023-10-18"),
    score: 88.4,
    isActive: true,
    notes: "Top performer of the month",
  },
  {
    id: 11,
    name: "Kevin",
    age: 34,
    registeredOn: new Date("2023-11-10"),
    score: 82.5,
    isActive: false,
    notes: "Pending reassignment",
  },
  {
    id: 12,
    name: "Laura",
    age: 24,
    registeredOn: new Date("2023-12-02"),
    score: 76.4,
    isActive: true,
    notes: "Strong contributor",
  },
  {
    id: 13,
    name: "Michael",
    age: 29,
    registeredOn: new Date("2024-01-14"),
    score: 93.2,
    isActive: true,
    notes: "Recognized for innovation",
  },
  {
    id: 14,
    name: "Nina",
    age: 21,
    registeredOn: new Date("2024-02-11"),
    score: 69.7,
    isActive: false,
    notes: "Training program enrollee",
  },
  {
    id: 15,
    name: "Oscar",
    age: 32,
    registeredOn: new Date("2024-03-05"),
    score: 81.3,
    isActive: true,
    notes: "Team lead",
  },
  {
    id: 16,
    name: "Paula",
    age: 27,
    registeredOn: new Date("2024-04-16"),
    score: 87.6,
    isActive: true,
    notes: "Reliable team player",
  },
  {
    id: 17,
    name: "Quincy",
    age: 35,
    registeredOn: new Date("2024-05-20"),
    score: 74.2,
    isActive: false,
    notes: "Currently unavailable",
  },
  {
    id: 18,
    name: "Rachel",
    age: 23,
    registeredOn: new Date("2024-06-08"),
    score: 91.1,
    isActive: true,
    notes: "Promising new hire",
  },
  {
    id: 19,
    name: "Steve",
    age: 28,
    registeredOn: new Date("2024-07-17"),
    score: 78.9,
    isActive: true,
    notes: "Strong leadership potential",
  },
  {
    id: 20,
    name: "Tina",
    age: 31,
    registeredOn: new Date("2024-08-22"),
    score: 80.4,
    isActive: true,
    notes: "Efficient task manager",
  },
  {
    id: 21,
    name: "Umar",
    age: 26,
    registeredOn: new Date("2024-09-05"),
    score: 86.5,
    isActive: true,
    notes: "Great interpersonal skills",
  },
  {
    id: 22,
    name: "Vera",
    age: 30,
    registeredOn: new Date("2024-10-12"),
    score: 83.7,
    isActive: true,
    notes: "Excellent communicator",
  },
  {
    id: 23,
    name: "Walter",
    age: 34,
    registeredOn: new Date("2024-11-03"),
    score: 72.9,
    isActive: false,
    notes: "Pending evaluation",
  },
  {
    id: 24,
    name: "Xena",
    age: 29,
    registeredOn: new Date("2024-12-01"),
    score: 89.2,
    isActive: true,
    notes: "Consistently high performer",
  },
  {
    id: 25,
    name: "Yvonne",
    age: 22,
    registeredOn: new Date("2025-01-10"),
    score: 70.6,
    isActive: false,
    notes: "Internship completed",
  },
];
