// src/data/dummyData.ts
export const dummyArray = [
  {
    id: 1,
    name: "Alice",
    age: 25,
    registeredOn: new Date("2023-01-15"),
    score: 89.5,
    isActive: true,
    notes: "First registered user",
    department: "Engineering",
    role: "Software Developer",
    address: "123 Main St, Lagos",
  },
  {
    id: 2,
    name: "Bob",
    age: 30,
    registeredOn: new Date("2023-02-20"),
    score: 75.0,
    isActive: false,
    notes: "On leave since June",
    department: "Marketing",
    role: "SEO Specialist",
    address: "456 Elm St, Abuja",
  },
  {
    id: 3,
    name: "Charlie",
    age: 35,
    registeredOn: new Date("2023-03-25"),
    score: 92.7,
    isActive: true,
    notes: "Recently promoted",
    department: "Finance",
    role: "Financial Analyst",
    address: "789 Pine Rd, Enugu",
  },
  {
    id: 4,
    name: "Diana",
    age: 28,
    registeredOn: new Date("2023-04-30"),
    score: 84.2,
    isActive: true,
    notes: "Part-time member",
    department: "Human Resources",
    role: "HR Assistant",
    address: "321 Oak Dr, Port Harcourt",
  },
  {
    id: 5,
    name: "Evan",
    age: 22,
    registeredOn: new Date("2023-05-15"),
    score: 68.4,
    isActive: false,
    notes: "Pending verification",
    department: "Engineering",
    role: "Intern",
    address: "654 Cedar Ln, Kano",
  },
  {
    id: 6,
    name: "Fiona",
    age: 29,
    registeredOn: new Date("2023-06-10"),
    score: 77.3,
    isActive: true,
    notes: "Recently joined the team",
    department: "Design",
    role: "UI/UX Designer",
    address: "987 Spruce Way, Ibadan",
  },
  {
    id: 7,
    name: "George",
    age: 33,
    registeredOn: new Date("2023-07-05"),
    score: 90.1,
    isActive: true,
    notes: "Key project contributor",
    department: "Engineering",
    role: "Tech Lead",
    address: "543 Maple Ave, Lagos",
  },
  {
    id: 8,
    name: "Hannah",
    age: 27,
    registeredOn: new Date("2023-08-01"),
    score: 73.8,
    isActive: false,
    notes: "Currently on sabbatical",
    department: "Operations",
    role: "Operations Manager",
    address: "678 Birch St, Abuja",
  },
  {
    id: 9,
    name: "Ian",
    age: 31,
    registeredOn: new Date("2023-09-12"),
    score: 85.6,
    isActive: true,
    notes: "Experienced mentor",
    department: "Training",
    role: "Training Coordinator",
    address: "246 Walnut Blvd, Enugu",
  },
  {
    id: 10,
    name: "Julia",
    age: 26,
    registeredOn: new Date("2023-10-18"),
    score: 88.4,
    isActive: true,
    notes: "Top performer of the month",
    department: "Engineering",
    role: "Backend Developer",
    address: "135 Redwood Rd, Lagos",
  },
  {
    id: 11,
    name: "Kevin",
    age: 34,
    registeredOn: new Date("2023-11-10"),
    score: 82.5,
    isActive: false,
    notes: "Pending reassignment",
    department: "Sales",
    role: "Sales Executive",
    address: "852 Cypress Ln, Kano",
  },
  {
    id: 12,
    name: "Laura",
    age: 24,
    registeredOn: new Date("2023-12-02"),
    score: 76.4,
    isActive: true,
    notes: "Strong contributor",
    department: "Customer Service",
    role: "Support Agent",
    address: "963 Poplar Dr, Port Harcourt",
  },
  {
    id: 13,
    name: "Michael",
    age: 29,
    registeredOn: new Date("2024-01-14"),
    score: 93.2,
    isActive: true,
    notes: "Recognized for innovation",
    department: "Engineering",
    role: "AI Specialist",
    address: "741 Willow St, Ibadan",
  },
  {
    id: 14,
    name: "Nina",
    age: 21,
    registeredOn: new Date("2024-02-11"),
    score: 69.7,
    isActive: false,
    notes: "Training program enrollee",
    department: "Training",
    role: "Trainee",
    address: "369 Sycamore Blvd, Abuja",
  },
  {
    id: 15,
    name: "Oscar",
    age: 32,
    registeredOn: new Date("2024-03-05"),
    score: 81.3,
    isActive: true,
    notes: "Team lead",
    department: "Engineering",
    role: "Frontend Developer",
    address: "159 Hazel Ave, Lagos",
  },
];
